### ISSUE TITLE
Cloudstack client would sometimes return an empty IP

### ISSUE THREAD

**Issue by synergiator** [xanzy/go-cloudstack#121]
In a GitLab autoscaling setup where Docker Machine is used to launch CloudStack VM, there is a chronical issue that the cloudstack seems to return to the driver an empty IP of the machine.

Example output from `docker-machine ls`:

`runner-nypcrwwr-gitlab-c1rollback-1569324315-926f2656   -        cloudstack   Running   tcp://:2376` 

Though, the machine is running and has an IP:

`ping runner-nypcrwwr-gitlab-c1rollback-1569324315-926f2656 `

```
PING runner-nypcrwwr-gitlab-c1rollback-1569324315-926f2656.cs50cloud.internal (172.16.1.233) 56(84) bytes of data.
64 bytes from runner-nypcrwwr-gitlab-c1rollback-1569324315-926f2656.cs50cloud.internal (172.16.1.233): icmp_seq=1 ttl=63 time=0.418 ms
```
The issue seems to be random that is sometimes more VMs have it, sometimes just one.

The driver does not has much logic so I suppose the cloudstack module might have an issue to ensure that a valid IP is returned instead of an empty field?

**Comment by 1605200517** [comment]
the code of the driver is public, yes (not my own).

Investigation of this problem in a production system seems to be a great chance to finally start learning Golang, ;-) that is I am trying to introduce a patch for the driver to make a wait loop for example instead of returning an empty IP. So far, I have found some golang developer discussions what should be the proper configuration for the dependency package manager to make it work properly. :-)

The source of the driver is:
https://github.com/andrestc/docker-machine-driver-cloudstack

**Comment by svanharmelen** [comment]
I'm really sorry, but I don't have time to take a closer look at this... Hope you made some progress in the mean time!

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this package has been moved to the Apache Foundation. Please find the new home for this package here: https://github.com/apache/cloudstack-go
