### ISSUE TITLE
compiling Terraform fails on Darwin / go 1.4 (cloudstack_disc, cloudstack_vpc)

### ISSUE THREAD

**Issue by pmoust** [xanzy/go-cloudstack#13]
https://github.com/xanzy/go-cloudstack/commit/bb608c839655e498170de29141c5e528be5edf56#diff-f6e1ea3f4446575b92e7cbd16db5bda2 introduced an `id string` param to `Volume.NewResizeVolumeParams` etc

Please check https://github.com/hashicorp/terraform/issues/788

**Comment by svanharmelen** [comment]
@pmoust the go-cloudstack package is actually fine, but is updated. When using the `cloudstack` package you are always using the latest version the package knows about and that one was just updated to 4.4 (was 4.3).

So that was causing the issues as the net version of the API seems to have a few backwards incompatible changes. Working on some updated code for TF, but in the meantime I will revert the changes here.

**Comment by pmoust** [comment]
Thanks for the swift response ;)
