### ISSUE TITLE
Apache CloudStack activities

### ISSUE THREAD

**Issue by synergiator** [xanzy/go-cloudstack#134]
Hi there,

FYI / maybe worth to know:

this project is one of [major dependencies](https://github.com/hashicorp/terraform-provider-cloudstack/blob/9ca483a88d6ba5559b241db5b537ad7eaaa417a1/vendor/modules.txt#L218) used in the Terraform provider for CloudStack.

Since that project has been archived recently by Terraform, the Apache CloudStack community is now investigating options to relocate the provider codebase to the community.

Source: Apache CloudStack public mailing list dev@cloudstack.apache.org

**Comment by svanharmelen** [comment]
Thanks for the heads up... I once (7 years ago) wrote this package as I needed it for the CloudStack provider, so not surprised it is still one of it's major dependencies 😏

Back then both this package and the provider were some of my earliest Go work, so I probably would not write it like this again today. Having all the code generated does make it quite easy to refactor it if needed, so that still makes sense. But the setup/style would probably be a lot different if I would have done it today...
