### ISSUE TITLE
iptonetworklist serialization

### ISSUE THREAD

**Issue by greut** [xanzy/go-cloudstack#87]
Hi,

A little bug report to inform your than `iptonetworklist` is more complex than `map[string]string`.

> **`iptonetworklist`** ip  to network mapping. Can't be specified with networkIds parameter.  Example:  `iptonetworklist[0].ip=10.10.10.11`, `iptonetworklist[0].ipv6=fc00:1234:5678::abcd`, `iptonetworklist[0].networkid=uuid`  - requests to use ip 10.10.10.11 in network id=uuid
> 
> http://cloudstack.apache.org/api/apidocs-4.10/apis/deployVirtualMachine.html

Thus the current implementation might not work as expected.

```go
	if v, found := p.p["iptonetworklist"]; found {
		i := 0
		for k, vv := range v.(map[string]string) {
			u.Set(fmt.Sprintf("iptonetworklist[%d].key", i), k)
			u.Set(fmt.Sprintf("iptonetworklist[%d].value", i), vv)
			i++
		}
	}
```

Cheers,

(**PS**: I don't need this anytime soon)

**Comment by svanharmelen** [comment]
Check... Thanks... Luckily this is already fixed once for the `details` maps, so maybe we should just add this one. I'll go and have a chat with our CloudStack devs to see if there is a way to learn which map is used in which way (as it seems there are two versions of how the data is expected for different endpoints).

**Comment by greut** [comment]
@svanharmelen `details` fits the `map[string]string` model though

**Comment by svanharmelen** [comment]
No trust me, they require the same format for sending data to the API: `details[0].key=value`

**Comment by svanharmelen** [comment]
@greut I think I see what you mean now. Turns out there are actually two issues with this.

One is about the format used to send map data. This is sometimes expected as `field[0].key=key&field[0].value=value` and sometimes as `field[0].key=value`. So I thought this issue was about the `iptonetworklist` field using the wrong format (like I just fixed for the `details` field).

But in case of the `iptonetworklist` field this is actually even more complicated, as there are 3 possible values for every list item:`ip`, `ipv6` and `networkid`.

So I think I need a special case for this one to solve it properly. Will have a closer look later on...

**Comment by greut** [comment]
Another example.

> _VM ID and IP map, `vmidipmap[0].vmid=1` `vmidipmap[0].ip=10.1.1.75`_
>
> https://doc.internal.exoscale.ch/others/cs/user/assignToLoadBalancerRule.html

https://github.com/xanzy/go-cloudstack/blob/master/cloudstack/LoadBalancerService.go#L364-L371

**Comment by svanharmelen** [comment]
I'm going to close this issue as I'm about to archive this repository. Development of this package has been moved to the Apache Foundation. Please find the new home for this package here: https://github.com/apache/cloudstack-go
